import customData from '../dataLocal.json';

const CovidLocalData = [
    {
      id: 1,
      backgroundColor: '#293077',
      judet: 'Alba',
      textColor: 'white',
      numberCases: customData[1],
    },
    {
      id: 2,
      backgroundColor: '#293077',
      judet: 'Arad',
      textColor: 'white',
      numberCases: customData[2],
    },
    {
      id: 3,
      backgroundColor: '#293077',
      judet: 'Argeș',
      textColor: 'white',
      numberCases: customData[3],
    },
    {
      id: 4,
      backgroundColor: '#293077',
      judet: 'Bacău',
      textColor: 'white',
      numberCases: customData[4],
    },
    {
      id: 5,
      backgroundColor: '#293077',
      judet: 'Bihor',
      textColor: 'white',
      numberCases: customData[5],
    },
    {
      id: 6,
      backgroundColor: '#293077',
      judet: 'Bistrița-Năsăud',
      textColor: 'white',
      numberCases: customData[6],
    },
    {
      id: 7,
      backgroundColor: '#293077',
      judet: 'Botoșani',
      textColor: 'white',
      numberCases: customData[7],
    },
    {
      id: 8,
      backgroundColor: '#293077',
      judet: 'Brașov',
      textColor: 'white',
      numberCases: customData[8],
    },
    {
      id: 9,
      backgroundColor: '#293077',
      judet: 'Brăila',
      textColor: 'white',
      numberCases: customData[9],
    },
    {
      id: 10,
      backgroundColor: '#293077',
      judet: 'Buzău',
      textColor: 'white',
      numberCases: customData[10],
    },
    {
      id: 11,
      backgroundColor: '#293077',
      judet: 'Caraș-Severin',
      textColor: 'white',
      numberCases: customData[11],
    },
    {
      id: 12,
      backgroundColor: '#293077',
      judet: 'Călărași',
      textColor: 'white',
      numberCases: customData[12],
    },
    {
      id: 13,
      backgroundColor: '#293077',
      judet: 'Cluj',
      textColor: 'white',
      numberCases: customData[13],
    },
    {
      id: 14,
      backgroundColor: '#293077',
      judet: 'Constanța',
      textColor: 'white',
      numberCases: customData[14],
    },
    {
      id: 15,
      backgroundColor: '#293077',
      judet: 'Covasna',
      textColor: 'white',
      numberCases: customData[15],
    },
    {
      id: 16,
      backgroundColor: '#293077',
      judet: 'Dâmbovița',
      textColor: 'white',
      numberCases: customData[16],
    },
    {
      id: 17,
      backgroundColor: '#293077',
      judet: 'Dolj',
      textColor: 'white',
      numberCases: customData[17],
    },
    {
      id: 18,
      backgroundColor: '#293077',
      judet: 'Galați',
      textColor: 'white',
      numberCases: customData[18],
    },
    {
      id: 19,
      backgroundColor: '#293077',
      judet: 'Giurgiu',
      textColor: 'white',
      numberCases: customData[19],
    },
    {
      id: 20,
      backgroundColor: '#293077',
      judet: 'Gorj',
      textColor: 'white',
      numberCases: customData[20],
    },
    {
      id: 21,
      backgroundColor: '#293077',
      judet: 'Harghita',
      textColor: 'white',
      numberCases: customData[21],
    },
    {
      id: 22,
      backgroundColor: '#293077',
      judet: 'Hunedoara',
      textColor: 'white',
      numberCases: customData[22],
    },
    {
      id: 23,
      backgroundColor: '#293077',
      judet: 'Ialomița',
      textColor: 'white',
      numberCases: customData[23],
    },
    {
      id: 24,
      backgroundColor: '#293077',
      judet: 'Iași',
      textColor: 'white',
      numberCases: customData[24],
    },
    {
      id: 25,
      backgroundColor: '#293077',
      judet: 'Ilfov',
      textColor: 'white',
      numberCases: customData[25],
    },
    {
        id: 26,
        backgroundColor: '#293077',
        judet: 'Maramureș',
        textColor: 'white',
        numberCases: customData[26],
        },
      {
        id: 27,
        backgroundColor: '#293077',
        judet: 'Mehedinți',
        textColor: 'white',
        numberCases: customData[27],
      },
      {
        id: 28,
        backgroundColor: '#293077',
        judet: 'Mureș',
        textColor: 'white',
        numberCases: customData[28],
      },
      {
        id: 29,
        backgroundColor: '#293077',
        judet: 'Neamț',
        textColor: 'white',
        numberCases: customData[29],
      },
      {
        id: 30,
        backgroundColor: '#293077',
        judet: 'Olt',
        textColor: 'white',
        numberCases: customData[30],
      },
      {
        id: 31,
        backgroundColor: '#293077',
        judet: 'Prahova',
        textColor: 'white',
        numberCases: customData[31],
      },
      {
        id: 32,
        backgroundColor: '#293077',
        judet: 'Satu Mare',
        textColor: 'white',
        numberCases: customData[32],
      },
      {
        id: 33,
        backgroundColor: '#293077',
        judet: 'Sălaj',
        textColor: 'white',
        numberCases: customData[33],
      },
      {
        id: 34,
        backgroundColor: '#293077',
        judet: 'Sibiu',
        textColor: 'white',
        numberCases: customData[34],
      },
      {
        id: 35,
        backgroundColor: '#293077',
        judet: 'Suceava',
        textColor: 'white',
        numberCases: customData[35],
      },
      {
      id: 36,
      backgroundColor: '#293077',
      judet: 'Teleorman',
      textColor: 'white',
      numberCases: customData[36],
    },
    {
      id: 37,
      backgroundColor: '#293077',
      judet: 'Timiș',
      textColor: 'white',
      numberCases: customData[37],
    },
    {
      id: 38,
      backgroundColor: '#293077',
      judet: 'Tulcea',
      textColor: 'white',
      numberCases: customData[38],
    },
    {
      id: 39,
      backgroundColor: '#293077',
      judet: 'Vaslui',
      textColor: 'white',
      numberCases: customData[39],
    },
    {
      id: 40,
      backgroundColor: '#293077',
      judet: 'Vâlcea',
      textColor: 'white',
      numberCases: customData[40],
    },
    {
      id: 41,
      backgroundColor: '#293077',
      judet: 'Vrancea',
      textColor: 'white',
      numberCases: customData[41],
    },
    {
      id: 42,
      backgroundColor: '#293077',
      judet: 'București',
      textColor: 'white',
      numberCases: customData[42],
    },
]

export default CovidLocalData